// --------------------------------------------------------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="Sven Erik Matzen">
//   (c) 2013 Sven Erik Matzen
// </copyright>
// <summary>
//   GlobalSuppressions.cs
// </summary>
// --------------------------------------------------------------------------------------------------------------------

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "WebSite", Scope = "namespace", Target = "Sem.Authentication.MvcHelper.WebSite.Models", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "WebSite", Scope = "namespace", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "WebSite", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "WebSite", Scope = "namespace", Target = "Sem.Authentication.MvcHelper.WebSite", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController.#.ctor()", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController.#Login(System.String)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController.#Login(System.String)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController.#Login(Sem.Authentication.MvcHelper.WebSite.Models.LoginViewModel,System.String)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController.#Login(Sem.Authentication.MvcHelper.WebSite.Models.LoginViewModel,System.String)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "login", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController.#Disassociate(System.String,System.String)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController.#ExternalLogin(System.String,System.String)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController.#ExternalLogin(System.String,System.String)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController.#ExternalLoginCallback(System.String)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController.#ExternalLoginCallback(System.String)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController.#LinkLogin(System.String)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController.#LinkLoginCallback()", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController.#ExternalLoginConfirmation(Sem.Authentication.MvcHelper.WebSite.Models.ExternalLoginConfirmationViewModel,System.String)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController.#ExternalLoginConfirmation(Sem.Authentication.MvcHelper.WebSite.Models.ExternalLoginConfirmationViewModel,System.String)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController.#ExternalLoginFailure()", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController+ManageMessageId.#RemoveLoginSuccess", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.AccountController+ChallengeResult.#ExecuteResult(System.Web.Mvc.ControllerContext)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "type", Target = "Sem.Authentication.MvcHelper.WebSite.Models.ExternalLoginConfirmationViewModel", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "type", Target = "Sem.Authentication.MvcHelper.WebSite.Models.LoginViewModel", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors", Scope = "type", Target = "Sem.Authentication.MvcHelper.WebSite.BundleConfig", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.BundleConfig.#RegisterBundles(System.Web.Optimization.BundleCollection)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors", Scope = "type", Target = "Sem.Authentication.MvcHelper.WebSite.FilterConfig", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.FilterConfig.#RegisterGlobalFilters(System.Web.Mvc.GlobalFilterCollection)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Controllers.HomeController.#Fault(System.String)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.MvcApplication.#Application_Start()", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Sem.Authentication.MvcHelper.WebSite.Startup.#ConfigureAuth(Owin.IAppBuilder)", Justification = "Review done 2014-01-09 Sven Erik Matzen")]
